spring.application.name=data-kinerja
server.port=8181
server.servlet.context-path=/api/v1

# --- DATABASE CONFIGURATION ---
# GANTI 'nama_db_kamu' dengan nama database yang sudah kamu buat di PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/datakinerja
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# --- FLYWAY CONFIGURATION ---
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
# Lokasi script migrasi (default-nya memang di sini, ditulis eksplisit biar jelas)
spring.flyway.locations=classpath:db/migration

# Mengurutkan folder (Tag) berdasarkan abjad (agar '1.' muncul sebelum '2.')
springdoc.swagger-ui.tags-sorter=alpha
# Mengurutkan method di dalam folder (GET, POST, PUT, DELETE)
springdoc.swagger-ui.operations-sorter=method

# --- LOGGING (Opsional, biar enak debug query) ---
logging.level.org.springframework.jdbc.core=DEBUG