CREATE TABLE tb_jenis_data
(
    id         SERIAL PRIMARY KEY,
    jenis_data VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);